version: '3.8'

services:
  rcon-cli-web:
    image: ghcr.io/xstar97/rcon-cli-web:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    #command: ["--port=3000", "--mode=light"]
    # set a custom port and other options via flags.
    # leave as default.
    # nothing here you need to change.

