version: '3.8'

services:
  rcon-cli-web:
    image: ghcr.io/xstar97/rcon-cli-web:latest
    environment:
      - PORT=3000
      - MODE=dark
      - CLI_DEFAULT_SERVER=default
      - CLI_CONFIG=/config/rcon.yaml
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
